# Generated by Django 3.1 on 2020-08-20 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20200818_1304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='survey',
            options={'permissions': (('view_results', 'View survey results'),)},
        ),
    ]
